#! /usr/bin/env python

import smtplib, sys, socket, time

#server = 'smtp.spray.se' # login below
#server = 'smtp.bahnhof.se'
server = 'localhost'

#try:
#    socket.getaddrinfo(server, 25)
#except:
#    time.sleep(1)

from email.mime.text import MIMEText

subject = sys.argv[1]
#fromaddr = "trurl@spray.se"
fromaddr = "trurl@yellow.worldforge.org"
toaddrs  = ["demitar"]
if subject.count('ember') > 0 and subject.count("error") > 0:
    toaddrs.append("erik@worldforge.org")

msg = MIMEText(sys.argv[2])

# me == the sender's email address
# you == the recipient's email address
msg['Subject'] = subject
msg['From'] = fromaddr
msg['To'] = ', '.join(toaddrs)

# Send the message via our own SMTP server, but don't include the
# envelope header.
s = smtplib.SMTP()
#s.set_debuglevel(1)
s.connect(server)
#s.login('trurl@spray.se', 'tr96653')
s.sendmail(fromaddr, toaddrs, msg.as_string())
s.quit()
